"""create payments table

Revision ID: 0aba65e17236
Revises: 423e708bf080
Create Date: 2026-07-04 23:42:44.418710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aba65e17236'
down_revision: Union[str, None] = '423e708bf080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_one_succeeded_payment_per_order', 'payments', ['order_id'], unique=True, postgresql_where=sa.text("status = 'SUCCEEDED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_succeeded_payment_per_order', table_name='payments', postgresql_where=sa.text("status = 'SUCCEEDED'"))
    op.drop_table('payments')
    # ### end Alembic commands ###
