"""add low_stock_threshold to products

Revision ID: 180d58cb134a
Revises: 47241cec9a06
Create Date: 2026-07-05 03:27:22.834645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180d58cb134a'
down_revision: Union[str, None] = '47241cec9a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "products",
        sa.Column(
            "low_stock_threshold",
            sa.Integer(),
            nullable=False,
            server_default="5",
        ),
    )

    op.alter_column(
        "products",
        "low_stock_threshold",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    # ### end Alembic commands ###
