"""fix payment unique constraint to allow retries after failure

Revision ID: 47241cec9a06
Revises: 0aba65e17236
Create Date: 2026-07-04 23:48:34.072399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47241cec9a06'
down_revision: Union[str, None] = '0aba65e17236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
